name: Trivy Scan

on:
  pull_request:

jobs:
  trivy-code-security-scan:
    runs-on: ubuntu-latest
    name: Trivy 
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Security Scan
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # 0.24.0
        with:
          scan-type: 'fs'
          scanners: vuln,secret
          exit-code: 1
          ignore-unfixed: true